### ISSUE TITLE
Build Spec build failure due to permissions issues

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/anoncreds-methods-registry#28]
The Build Spec job is failing due to what appears to be permissions issues.

The latest failure:
https://github.com/hyperledger/anoncreds-methods-registry/actions/runs/10370892120

![image](https://github.com/user-attachments/assets/f10e842d-b0d7-48f2-8440-bb5998668f3c)

Last worked here:
https://github.com/hyperledger/anoncreds-methods-registry/actions/runs/5080617892

**Comment by WadeBarnes** [comment]
@ryjones, are you able to look in on the `secrets.GITHUB_TOKEN` and see if it's expired or needs to be replaced for some other reason?  Thanks

**Comment by WadeBarnes** [comment]
@swcurran, Also wondering if the permissions need to be stated on the job:

```
permissions:
  contents: write
```

As shown here; https://github.com/JamesIves/github-pages-deploy-action?tab=readme-ov-file#getting-started-airplane 

![image](https://github.com/user-attachments/assets/d0edf0c9-b772-4b0b-9394-29d9b440c65f)

**Comment by swcurran** [comment]
That fixed it.  I had been comparing with another publish job and saw that, but since this one didn’t have it before, I didn’t add it.  Now there and now working — thanks!
